// Kimcare/src/components/Navbar.vue
<template>
  <nav class="bg-royalblue text-white p-4 flex justify-between">
    <h1 class="text-xl font-bold">Kimcare Psychologies</h1>
    <ul class="flex space-x-4">
      <li><router-link to="/" class="hover:text-junglegreen">Home</router-link></li>
      <li><router-link to="/donate" class="hover:text-junglegreen">Donate</router-link></li>
      <li><router-link to="/volunteer" class="hover:text-junglegreen">Volunteer</router-link></li>
      <li><router-link to="/learn" class="hover:text-junglegreen">Learn</router-link></li>
      <li><router-link to="/community" class="hover:text-junglegreen">Community</router-link></li>
    </ul>
  </nav>
</template>

// client/src/components/layout/navbar.tsx
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

export default function Navbar() {
  return (
    <nav className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-16 items-center px-4">
        <Link href="/">
          <a className="mr-8 flex items-center space-x-2">
            <span className="text-xl font-bold">KIMCARE</span>
          </a>
        </Link>
        <div className="flex items-center justify-between flex-1">
          <div className="flex gap-6 md:gap-10">
            <Link href="/resources">
              <a className="text-sm font-medium transition-colors hover:text-primary">
                Resources
              </a>
            </Link>
            <Link href="/volunteer">
              <a className="text-sm font-medium transition-colors hover:text-primary">
                Volunteer
              </a>
            </Link>
            <Link href="/partners">
              <a className="text-sm font-medium transition-colors hover:text-primary">
                Partners
              </a>
            </Link>
          </div>
          <Link href="/donate">
            <Button variant="default">Donate Now</Button>
          </Link>
        </div>
      </div>
    </nav>
  );
}
